"use strict";

// AUTO-GENERATED by scripts/sync-jlive-links.ts (in the FestFlow repo) — do
// not hand-edit. Re-run it (with this repo checked out) to refresh this
// from FestFlow's prisma/seed-data/festivals.json.
const FESTFLOW_FESTIVALS_BY_ARTIST = {
  "『ユイカ』": [
    {
      "slug": "rock-in-japan-festival-2026",
      "name": "ROCK IN JAPAN FESTIVAL 2026"
    },
    {
      "slug": "rising-sun-rock-festival-2026",
      "name": "RISING SUN ROCK FESTIVAL 2026 in EZO"
    },
    {
      "slug": "arabaki-rock-fest-2026",
      "name": "ARABAKI ROCK FEST.26"
    }
  ],
  "ano": [
    {
      "slug": "rock-in-japan-festival-2026",
      "name": "ROCK IN JAPAN FESTIVAL 2026"
    },
    {
      "slug": "rising-sun-rock-festival-2026",
      "name": "RISING SUN ROCK FESTIVAL 2026 in EZO"
    }
  ],
  "Chilli Beans.": [
    {
      "slug": "rock-in-japan-festival-2026",
      "name": "ROCK IN JAPAN FESTIVAL 2026"
    },
    {
      "slug": "metrock-tokyo-2026",
      "name": "METROCK 2026 (Tokyo)"
    }
  ],
  "CUTIE STREET": [
    {
      "slug": "rock-in-japan-festival-2026",
      "name": "ROCK IN JAPAN FESTIVAL 2026"
    }
  ],
  "Dannie May": [
    {
      "slug": "metrock-tokyo-2026",
      "name": "METROCK 2026 (Tokyo)"
    }
  ],
  "Fujii Kaze": [
    {
      "slug": "fuji-rock-festival-2026",
      "name": "FUJI ROCK FESTIVAL '26"
    }
  ],
  "go!go!vanillas": [
    {
      "slug": "rock-in-japan-festival-2026",
      "name": "ROCK IN JAPAN FESTIVAL 2026"
    },
    {
      "slug": "greenroom-festival-2026",
      "name": "GREENROOM FESTIVAL '26"
    },
    {
      "slug": "metrock-tokyo-2026",
      "name": "METROCK 2026 (Tokyo)"
    }
  ],
  "KANA-BOON": [
    {
      "slug": "rock-in-japan-festival-2026",
      "name": "ROCK IN JAPAN FESTIVAL 2026"
    },
    {
      "slug": "metrock-tokyo-2026",
      "name": "METROCK 2026 (Tokyo)"
    },
    {
      "slug": "viva-la-rock-2026",
      "name": "VIVA LA ROCK 2026"
    }
  ],
  "luv": [
    {
      "slug": "arabaki-rock-fest-2026",
      "name": "ARABAKI ROCK FEST.26"
    }
  ],
  "muque": [
    {
      "slug": "rock-in-japan-festival-2026",
      "name": "ROCK IN JAPAN FESTIVAL 2026"
    },
    {
      "slug": "metrock-tokyo-2026",
      "name": "METROCK 2026 (Tokyo)"
    }
  ],
  "natori": [
    {
      "slug": "rock-in-japan-festival-2026",
      "name": "ROCK IN JAPAN FESTIVAL 2026"
    },
    {
      "slug": "rising-sun-rock-festival-2026",
      "name": "RISING SUN ROCK FESTIVAL 2026 in EZO"
    },
    {
      "slug": "viva-la-rock-2026",
      "name": "VIVA LA ROCK 2026"
    }
  ],
  "NOMELON NOLEMON": [
    {
      "slug": "rock-in-japan-festival-2026",
      "name": "ROCK IN JAPAN FESTIVAL 2026"
    }
  ],
  "Novelbright": [
    {
      "slug": "rock-in-japan-festival-2026",
      "name": "ROCK IN JAPAN FESTIVAL 2026"
    },
    {
      "slug": "metrock-tokyo-2026",
      "name": "METROCK 2026 (Tokyo)"
    }
  ],
  "Sunny Day Service": [
    {
      "slug": "fuji-rock-festival-2026",
      "name": "FUJI ROCK FESTIVAL '26"
    }
  ],
  "Vaundy": [
    {
      "slug": "rock-in-japan-festival-2026",
      "name": "ROCK IN JAPAN FESTIVAL 2026"
    },
    {
      "slug": "rising-sun-rock-festival-2026",
      "name": "RISING SUN ROCK FESTIVAL 2026 in EZO"
    }
  ],
  "yutori": [
    {
      "slug": "metrock-tokyo-2026",
      "name": "METROCK 2026 (Tokyo)"
    }
  ],
  "YUURI": [
    {
      "slug": "rock-in-japan-festival-2026",
      "name": "ROCK IN JAPAN FESTIVAL 2026"
    },
    {
      "slug": "metrock-tokyo-2026",
      "name": "METROCK 2026 (Tokyo)"
    },
    {
      "slug": "arabaki-rock-fest-2026",
      "name": "ARABAKI ROCK FEST.26"
    }
  ]
};

function festflowFestivalsFor(artist) {
  return FESTFLOW_FESTIVALS_BY_ARTIST[artist] || [];
}

module.exports = { festflowFestivalsFor };
